### ISSUE TITLE
Having trouble getting this to  work

### ISSUE THREAD

**Issue by ghost** [renfredxh/tmx#1]
Hi. First of all, I must say thanks for putting this up. It must have taken ages to write this! Unfortunately though, I'm having a bit of trouble running it. I've only ever made bassic games before, never used tiles. I'm sure that it's something that I've done wrong, something silly. I made a new, very basic map and saved it as 'my_map.tmx' in a folder in python. Then I copied and pasted tmx and saved it in the same folder. Then I copied your basic code just to see if it runs. My first problem was 'no such file exists' - I saved it as my_map and not myMap lol. After changing this silly little mistake I goot this error:

Traceback (most recent call last):
  File "C:/Python33/tile test/map_test.py", line 10, in <module>
    tilemap = tmx.load('my_map.tmx', screen.get_size())
  File "C:/Python33/tile test\tmx.py", line 841, in load
    return TileMap.load(filename, viewport)
  File "C:/Python33/tile test\tmx.py", line 720, in load
    layer = Layer.fromxml(tag, tilemap)
  File "C:/Python33/tile test\tmx.py", line 259, in fromxml
    tile = map.tilesets[gid]
KeyError: 1610612764

I don't konw what keyError means! It's probably something very silly though. I would really appreciate it if you could give me some advice, because I'm really not sure what to do, but I really would like this to work so that I could make some half decent games lol. Hopefully you'll have some idea on how to sort this.
Thanks!
Dan

**Comment by ghost** [comment]
Forget what I said, it seems to have been a problem with the map (thought it would be lol). Not entirely sure what the problem was though. I made a new map and loaded it and it worked perfectly. God knows what the problem was wiit that other map. Oh well, all sorted now. 
Thanks!
Dan
